#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <CL/cl.h>
#include <CL/cl_gl.h>

#include "cl_rename_api.h"
#include "cl_util.h"

CLIicdDispatchTable *g_icd_dispatchTable = NULL;

#define ICD_DISPATCH_TABLE_ENTRY(fn)       \
  assert(dispatchTable->entryCount < 256); \
  dispatchTable->entries[dispatchTable->entryCount++] = (void *)(intptr_t)(fn)

cl_int cliIcdDispatchTableCreate(void) {
  CLIicdDispatchTable *dispatchTable = (CLIicdDispatchTable *)DFCL_NEW(CLIicdDispatchTable);
  if (!dispatchTable) {
    return CL_OUT_OF_HOST_MEMORY;
  }
  memset(dispatchTable, 0, sizeof(*dispatchTable));

  /* OpenCL 1.0 */
#ifdef CL_ENABLE_ICD2
  ICD_DISPATCH_TABLE_ENTRY(CL_ICD2_TAG_KHR);
#else
  ICD_DISPATCH_TABLE_ENTRY(clGetPlatformIDs);
#endif
  ICD_DISPATCH_TABLE_ENTRY(clGetPlatformInfo);
  ICD_DISPATCH_TABLE_ENTRY(clGetDeviceIDs);
  ICD_DISPATCH_TABLE_ENTRY(clGetDeviceInfo);
  ICD_DISPATCH_TABLE_ENTRY(clCreateContext);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(clRetainContext);
  ICD_DISPATCH_TABLE_ENTRY(clReleaseContext);
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* ICD_DISPATCH_TABLE_ENTRY ( clGetContextInfo              ); */
  ICD_DISPATCH_TABLE_ENTRY(clCreateCommandQueue);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(clReleaseCommandQueue);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clCreateProgramWithBinary */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clReleaseProgram */
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clBuildProgram */
#ifdef CL_ENABLE_ICD2
  ICD_DISPATCH_TABLE_ENTRY(NULL);
#else
  ICD_DISPATCH_TABLE_ENTRY(NULL);
#endif
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clCreateKernel */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clReleaseKernel */
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clSetKernelArg */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clFinish */
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clEnqueueReadBuffer */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clEnqueueNDRangeKernel */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* cl_khr_d3d10_sharing (windows-only) */
#if 0 && defined(_WIN32)
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
#else
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
#endif

  /* OpenCL 1.1 */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* cl_ext_device_fission */
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clCreateSubDevicesEXT */
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clRetainDeviceEXT */
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clReleaseDeviceEXT */

  /* cl_khr_gl_event */
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* OpenCL 1.2 */
  ICD_DISPATCH_TABLE_ENTRY(clCreateSubDevices);
  ICD_DISPATCH_TABLE_ENTRY(clRetainDevice);
  ICD_DISPATCH_TABLE_ENTRY(clReleaseDevice);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* cl_khr_d3d11_sharing */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* cl_khr_dx9_media_sharing */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* cl_khr_egl_image */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* cl_khr_egl_event */
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* OpenCL 2.0 */
  ICD_DISPATCH_TABLE_ENTRY(NULL); /* clCreateCommandQueueWithProperties */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* cl_khr_sub_groups */
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* OpenCL 2.1 */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* OpenCL 2.2 */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  /* OpenCL 3.0 */
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);
  ICD_DISPATCH_TABLE_ENTRY(NULL);

  g_icd_dispatchTable = dispatchTable;
  return CL_SUCCESS;
}

void cliIcdDispatchTableDestroy(CLIicdDispatchTable *dispatchTable) {
  DFCL_MEM_FREE(dispatchTable);
}
